### ISSUE TITLE
Crash without layout

### ISSUE THREAD

**Issue by psi-4ward** [haraldrudell/uinexpress#1]
Got a crash without a layout:
`Error: ENOENT, open '.../views/layout.tpl'`

I think the express3 has no longer a layout option?

**Comment by haraldrudell** [comment]
This project was a hack to see what it would be like to use underscore server side. It is not supported and does not even have unit tests. I wrote my own rendering because I could not find what I wanted.

express3 does not have templates. There's a package doing that. If you set layout to false this project should work.

I don't see how you get three dots in your template name, though. looks like bad news to me. Have fun!

This is a won't fix. Sorry.
